---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-out
  labels:
    app-name: jaeger
  namespace: observe
spec:
  type: NodePort
  ports:
  - port: 16686
  selector:
    app-name: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  labels:
    app-name: jaeger
  namespace: observe
spec:
  ports:
  - port: 5775
    name: udp1
    protocol: UDP
  - port: 5778
    name: tcp1
  - port: 6831
    name: udp2
    protocol: UDP
  - port: 6832
    name: udp3
    protocol: UDP
  - port: 14250
    name: tcp2
  - port: 14268
    name: tcp3
  - port: 4317
    name: otlp-grpc
  - port: 4318
    name: otlp-http
  selector:
    app-name: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-agent
  labels:
    app-name: jaeger
  namespace: observe
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: jaeger
  template:
    metadata:
      labels:
        app-name: jaeger
      name: jaeger-agent
    spec:
      containers:
      - name: jaeger-agent
        image: jaegertracing/all-in-one:1.57
        args:
        - "--collector.otlp.enabled=true"
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 14250
          protocol: TCP
        - containerPort: 4317
          protocol: TCP
        - containerPort: 4318
          protocol: TCP
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
      restartPolicy: Always
